// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Run `npm run optimize:images` to regenerate after changing files in /assets.

export const teamPhoto = {
  "alt": "The TUT Colour Fun Run organising team — Sport Management students at the Tshwane University of Technology Pretoria Campus.",
  "width": 1024,
  "height": 1365,
  "jpg": "/team/team-1024.b6292219.jpg",
  "avif": "/team/team-480.b6292219.avif 480w, /team/team-768.b6292219.avif 768w, /team/team-1024.b6292219.avif 1024w",
  "webp": "/team/team-480.b6292219.webp 480w, /team/team-768.b6292219.webp 768w, /team/team-1024.b6292219.webp 1024w",
  "blurDataURL": "data:image/webp;base64,UklGRtgAAABXRUJQVlA4IMwAAADwBQCdASoYACAAPu1kqU2ppaQiMAgBMB2JZgCdITugxBfpL292eFlx1D9D+rItbpat9XtVd3vG2AD+F85poLMPGmwbp0mxi6RvE+LLGu1S5iE7lIHro5iZ199pbkdvKNrCOuLgC59D43aqwUQkd7eb13uc2Jk7RiTsb/KiBJNqVINPTsfI3pRIb3egtTVchmcuwq+mixYvhWgkG4j2YibBKNjDOlHeeawyBVr9poa0huefii3z6GaKuvq1c6pa/zS19LQRtbRO0MAAAAA="
} as const;

export const tutLogo = {
  "alt": "Tshwane University of Technology logo",
  "webp": "/logo/logo.b6ae9b5b.webp",
  "png": "/logo/logo.b6ae9b5b.png",
  "width": 256,
  "height": 166
} as const;
