/**
 * Pre-generates fully-optimized, responsive image assets for the static export.
 *
 * Why: the site uses `output: "export"` (images.unoptimized), so Next's runtime
 * optimizer is off. We bake AVIF + WebP + a JPEG fallback at several widths, plus
 * a tiny inline blur placeholder, and emit `src/lib/media.ts` with the metadata.
 *
 * Output filenames are content-hashed (e.g. team-480.a1b2c3d4.avif) so they can be
 * cached `immutable` for a year on Vercel — the hash only changes if the source does.
 *
 * Run:  npm run optimize:images   (after changing anything in assets/)
 */
import sharp from "sharp";
import { mkdir, writeFile, rm, readFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const asset = (p) => path.join(ROOT, "assets", p);
const pub = (p) => path.join(ROOT, "public", p);

const TEAM_WIDTHS = [480, 768, 1024];
const TEAM_ALT =
  "The TUT Colour Fun Run organising team — Sport Management students at the Tshwane University of Technology Pretoria Campus.";
const LOGO_ALT = "Tshwane University of Technology logo";

const hash8 = (buf) => createHash("sha256").update(buf).digest("hex").slice(0, 8);

async function buildTeam() {
  await rm(pub("team"), { recursive: true, force: true });
  await mkdir(pub("team"), { recursive: true });
  const src = await readFile(asset("team-src.jpg"));
  const h = hash8(src);
  const base = () => sharp(src).rotate(); // bake EXIF orientation

  for (const w of TEAM_WIDTHS) {
    await base().resize({ width: w }).avif({ quality: 52, effort: 4 }).toFile(pub(`team/team-${w}.${h}.avif`));
    await base().resize({ width: w }).webp({ quality: 74 }).toFile(pub(`team/team-${w}.${h}.webp`));
  }
  const fallback = await base()
    .resize({ width: 1024 })
    .jpeg({ quality: 78, mozjpeg: true })
    .toBuffer({ resolveWithObject: true });
  await writeFile(pub(`team/team-1024.${h}.jpg`), fallback.data);

  const blur = await base().resize({ width: 24 }).webp({ quality: 40 }).toBuffer();

  return {
    alt: TEAM_ALT,
    width: fallback.info.width,
    height: fallback.info.height,
    jpg: `/team/team-1024.${h}.jpg`,
    avif: TEAM_WIDTHS.map((w) => `/team/team-${w}.${h}.avif ${w}w`).join(", "),
    webp: TEAM_WIDTHS.map((w) => `/team/team-${w}.${h}.webp ${w}w`).join(", "),
    blurDataURL: `data:image/webp;base64,${blur.toString("base64")}`,
  };
}

async function buildLogo() {
  await rm(pub("logo"), { recursive: true, force: true });
  await mkdir(pub("logo"), { recursive: true });
  const src = await readFile(asset("logo-src.jpg"));
  const h = hash8(src);
  // Trim the white border so the emblem fills the frame (reads bigger in the nav chip).
  const mk = () => sharp(src).trim({ background: "#ffffff", threshold: 25 });
  const out = await mk().resize({ width: 256 }).webp({ quality: 92 }).toBuffer({ resolveWithObject: true });
  await writeFile(pub(`logo/logo.${h}.webp`), out.data);
  await mk().resize({ width: 256 }).png({ palette: true, quality: 90 }).toFile(pub(`logo/logo.${h}.png`));

  return {
    alt: LOGO_ALT,
    webp: `/logo/logo.${h}.webp`,
    png: `/logo/logo.${h}.png`,
    width: out.info.width,
    height: out.info.height,
  };
}

const team = await buildTeam();
const logo = await buildLogo();

const file = `// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Run \`npm run optimize:images\` to regenerate after changing files in /assets.

export const teamPhoto = ${JSON.stringify(team, null, 2)} as const;

export const tutLogo = ${JSON.stringify(logo, null, 2)} as const;
`;
await writeFile(path.join(ROOT, "src", "lib", "media.ts"), file);

console.log("✓ team:", team.width + "x" + team.height, "| logo:", logo.width + "x" + logo.height);
console.log("✓ wrote src/lib/media.ts (content-hashed assets)");
